# Generated Python code from HTML
def generate_html():
    """Function that returns the HTML content"""
    from html import escape

    return """\
<!DOCTYPE html>\n"
        "<html lang=\"vi\" class=\"light\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Dashboard Kiểm Soát Ca Tồn & Triển Khai (Bảo Trì & TK)</title>\n"
        "    <!-- Tailwind CSS CDN -->\n"
        "    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
        "    <!-- Chart.js CDN -->\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
        "    <!-- SheetJS (xlsx) CDN -->\n"
        "    <script src=\"https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js\"></script>\n"
        "    <!-- FontAwesome CDN -->\n"
        "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n"
        "    <!-- Google Fonts: Inter -->\n"
        "    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
        "    \n"
        "    <script>\n"
        "        tailwind.config = {\n"
        "            darkMode: \'class\',\n"
        "            theme: {\n"
        "                extend: {\n"
        "                    colors: {\n"
        "                        paleOlive: {\n"
        "                            50: \'#f7f9f2\',\n"
        "                            100: \'#e9efdc\',\n"
        "                            200: \'#d4e1bd\',\n"
        "                            300: \'#b7ce96\',\n"
        "                            400: \'#94b36c\',\n"
        "                            500: \'#759948\',\n"
        "                            600: \'#5c7b35\',\n"
        "                            700: \'#465e28\',\n"
        "                            800: \'#3a4e23\',\n"
        "                            900: \'#30411d\',\n"
        "                            950: \'#1a250e\'\n"
        "                        }\n"
        "                    },\n"
        "                    fontFamily: {\n"
        "                        sans: [\'Inter\', \'sans-serif\'],\n"
        "                    }\n"
        "                }\n"
        "            }\n"
        "        }\n"
        "    </script>\n"
        "    <style>\n"
        "        body { font-family: \'Inter\', sans-serif; }\n"
        "        .custom-scrollbar::-webkit-scrollbar { width: 6px; height: 6px; }\n"
        "        .custom-scrollbar::-webkit-scrollbar-track { background: #f1f5f9; }\n"
        "        .custom-scrollbar::-webkit-scrollbar-thumb { background: #b7ce96; border-radius: 4px; }\n"
        "        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #759948; }\n"
        "        .col-highlight { background-color: #f7f9f2 !important; }\n"
        "        .dark .col-highlight { background-color: rgba(117, 153, 72, 0.15) !important; }\n"
        "    </style>\n"
        "</head>\n"
        "<body class=\"bg-gray-50 dark:bg-slate-900 text-gray-800 dark:text-gray-100 antialiased min-h-screen flex flex-col transition-colors duration-200\">\n"
        "\n"
        "    <!-- Toast Notification Container -->\n"
        "    <div id=\"toastContainer\" class=\"fixed top-5 right-5 z-50 flex flex-col gap-2 pointer-events-none\"></div>\n"
        "\n"
        "    <!-- Top Navigation Bar -->\n"
        "    <header class=\"bg-white dark:bg-slate-800 border-b border-paleOlive-200 dark:border-slate-700 sticky top-0 z-30 shadow-sm\">\n"
        "        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between gap-4\">\n"
        "            <div class=\"flex items-center space-x-3\">\n"
        "                <div class=\"w-10 h-10 rounded-xl bg-paleOlive-500 flex items-center justify-center text-white font-bold text-lg shadow-md shadow-paleOlive-200 dark:shadow-none\">\n"
        "                    <i class=\"fa-solid fa-chart-line\"></i>\n"
        "                </div>\n"
        "                <div>\n"
        "                    <h1 class=\"font-bold text-gray-900 dark:text-white text-base sm:text-lg leading-tight\">DASHBOARD KIỂM SOÁT CA TỒN & TRIỂN KHAI</h1>\n"
        "                    <p class=\"text-xs text-paleOlive-600 dark:text-paleOlive-400 font-medium hidden sm:block\">Hệ Thống Theo Dõi Vận Hành & Kiểm Soát Chuẩn Realtime</p>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Sheet Switcher Tabs -->\n"
        "            <div class=\"flex bg-paleOlive-100 dark:bg-slate-700 p-1 rounded-xl border border-paleOlive-200 dark:border-slate-600\">\n"
        "                <button id=\"btnSheetTon\" onclick=\"switchSheet(\'Ton\')\" class=\"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 bg-paleOlive-500 text-white shadow-sm\">\n"
        "                    <i class=\"fa-solid fa-list-check\"></i>\n"
        "                    <span>SHEET TỒN (BẢO TRÌ)</span>\n"
        "                </button>\n"
        "                <button id=\"btnSheetTK\" onclick=\"switchSheet(\'TK\')\" class=\"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 text-paleOlive-800 dark:text-paleOlive-200 hover:bg-paleOlive-200/60 dark:hover:bg-slate-600\">\n"
        "                    <i class=\"fa-solid fa-truck-fast\"></i>\n"
        "                    <span>SHEET TK (TRIỂN KHAI)</span>\n"
        "                </button>\n"
        "            </div>\n"
        "\n"
        "            <div class=\"flex items-center space-x-2\">\n"
        "                <label for=\"excelFileInput\" class=\"cursor-pointer bg-paleOlive-500 hover:bg-paleOlive-600 text-white px-3 py-2 rounded-lg text-xs font-medium transition flex items-center gap-1.5 shadow-sm\">\n"
        "                    <i class=\"fa-solid fa-file-excel text-sm\"></i>\n"
        "                    <span class=\"hidden md:inline\">Cập nhật File Excel</span>\n"
        "                </label>\n"
        "                <input type=\"file\" id=\"excelFileInput\" accept=\".xlsx, .xls, .csv\" class=\"hidden\" onchange=\"handleFileUpload(event)\">\n"
        "\n"
        "                <button onclick=\"exportDataCSV()\" class=\"bg-blue-600 hover:bg-blue-700 text-white px-3 py-2 rounded-lg text-xs font-medium transition flex items-center gap-1.5 shadow-sm\" title=\"Xuất dữ liệu CSV/Excel\">\n"
        "                    <i class=\"fa-solid fa-download\"></i>\n"
        "                    <span class=\"hidden md:inline\">Export</span>\n"
        "                </button>\n"
        "\n"
        "                <button onclick=\"toggleDarkMode()\" class=\"p-2 rounded-lg text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-700 transition\" title=\"Đổi giao diện Sáng / Tối\">\n"
        "                    <i class=\"fa-solid fa-moon dark:hidden text-base\"></i>\n"
        "                    <i class=\"fa-solid fa-sun hidden dark:inline text-base text-amber-400\"></i>\n"
        "                </button>\n"
        "            </div>\n"
        "        </div>\n"
        "    </header>\n"
        "\n"
        "    <!-- Main Container -->\n"
        "    <main class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6 flex-1 w-full\">\n"
        "\n"
        "        <!-- Info Banner for Active Sheet -->\n"
        "        <div id=\"infoBanner\" class=\"bg-paleOlive-50 dark:bg-paleOlive-950/40 border-l-4 border-paleOlive-500 p-4 rounded-r-xl shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-3 border border-paleOlive-200 dark:border-paleOlive-800\">\n"
        "            <div class=\"flex items-start space-x-3\">\n"
        "                <i class=\"fa-solid fa-circle-info text-paleOlive-700 dark:text-paleOlive-300 text-lg mt-0.5\"></i>\n"
        "                <div class=\"text-xs text-paleOlive-950 dark:text-paleOlive-100 space-y-1\">\n"
        "                    <p class=\"font-semibold text-sm\" id=\"bannerTitle\">Các trường thông tin kiểm soát trọng yếu (Bảo Trì):</p>\n"
        "                    <div class=\"flex flex-wrap gap-2 pt-1\" id=\"bannerBadges\">\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Số HĐ</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Khách Hàng</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Block</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Lần Hẹn</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">CL Lặp</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Nhân Sự</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Quản Lý</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Tồn Giờ</span>\n"
        "                        <span class=\"bg-paleOlive-200/80 dark:bg-paleOlive-800/60 px-2 py-0.5 rounded text-paleOlive-900 dark:text-paleOlive-100 font-medium\">Kiểm Soát</span>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "            <div class=\"text-right text-xs text-gray-500 dark:text-gray-400 whitespace-nowrap self-end md:self-center\">\n"
        "                Dữ liệu hiện tại: <span id=\"recordCountBadge\" class=\"font-bold text-gray-800 dark:text-gray-200\">0</span> ca\n"
        "            </div>\n"
        "        </div>\n"
        "\n"
        "        <!-- KPI Metrics Grid -->\n"
        "        <div class=\"grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 sm:gap-4\" id=\"kpiContainer\">\n"
        "            <!-- Dynamically Rendered KPIs -->\n"
        "        </div>\n"
        "\n"
        "        <!-- Filter Toolbar -->\n"
        "        <div class=\"bg-white dark:bg-slate-800 p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm space-y-3\">\n"
        "            <div class=\"flex flex-wrap items-center justify-between gap-3\">\n"
        "                <div class=\"flex items-center gap-2 text-paleOlive-800 dark:text-paleOlive-300 font-semibold text-sm\">\n"
        "                    <i class=\"fa-solid fa-filter text-paleOlive-600 dark:text-paleOlive-400\"></i>\n"
        "                    <span>BỘ LỌC DỮ LIỆU CONTROL</span>\n"
        "                </div>\n"
        "                <div class=\"flex items-center gap-3\">\n"
        "                    <button onclick=\"resetFilters()\" class=\"text-xs text-paleOlive-700 dark:text-paleOlive-300 hover:text-paleOlive-900 font-medium px-3 py-1.5 rounded-md hover:bg-paleOlive-100 dark:hover:bg-slate-700 border border-paleOlive-200 dark:border-slate-600 transition\">\n"
        "                        <i class=\"fa-solid fa-rotate-right mr-1\"></i> Xóa Lọc\n"
        "                    </button>\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <div class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3\" id=\"filterInputsGroup\">\n"
        "                <!-- Dynamic Filters per Sheet -->\n"
        "            </div>\n"
        "        </div>\n"
        "\n"
        "        <!-- Charts Section -->\n"
        "        <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4\" id=\"chartsGrid\">\n"
        "            <!-- Dynamically populated chart cards -->\n"
        "        </div>\n"
        "\n"
        "        <!-- Table Section -->\n"
        "        <div class=\"bg-white dark:bg-slate-800 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm overflow-hidden\">\n"
        "            <div class=\"p-4 border-b border-paleOlive-200 dark:border-slate-700 bg-paleOlive-50/50 dark:bg-slate-800/80 flex flex-wrap justify-between items-center gap-3\">\n"
        "                <div>\n"
        "                    <h2 class=\"font-bold text-gray-900 dark:text-white text-base\" id=\"tableTitle\">BẢNG KIỂM SOÁT DỮ LIỆU TỒN CA (BẢO TRÌ)</h2>\n"
        "                    <p class=\"text-xs text-paleOlive-700 dark:text-paleOlive-400\">Xem, tìm kiếm, lọc và cập nhật trực tiếp trạng thái Kiểm Soát</p>\n"
        "                </div>\n"
        "                <div class=\"text-xs font-semibold px-3 py-1.5 rounded-lg bg-paleOlive-100 dark:bg-paleOlive-900/40 text-paleOlive-800 dark:text-paleOlive-200 border border-paleOlive-200 dark:border-paleOlive-800\">\n"
        "                    Hiển thị: <span id=\"displayedCount\" class=\"text-paleOlive-900 dark:text-white font-bold\">0</span> / <span id=\"totalCount\" class=\"text-paleOlive-900 dark:text-white font-bold\">0</span> ca\n"
        "                </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Scrollable Table -->\n"
        "            <div class=\"overflow-x-auto custom-scrollbar\">\n"
        "                <table class=\"w-full text-left text-xs border-collapse\">\n"
        "                    <thead id=\"tableHeader\" class=\"bg-paleOlive-100 dark:bg-paleOlive-900/60 text-paleOlive-900 dark:text-paleOlive-200 font-bold uppercase tracking-wider border-b border-paleOlive-200 dark:border-slate-700\">\n"
        "                        <!-- Rendered via JS -->\n"
        "                    </thead>\n"
        "                    <tbody id=\"tableBody\" class=\"divide-y divide-paleOlive-100 dark:divide-slate-700/60 bg-paleOlive-50/20 dark:bg-slate-900/20 text-gray-700 dark:text-gray-300\">\n"
        "                        <!-- Rendered via JS -->\n"
        "                    </tbody>\n"
        "                </table>\n"
        "            </div>\n"
        "            \n"
        "            <div class=\"p-3 bg-paleOlive-50 dark:bg-slate-800/60 border-t border-paleOlive-200 dark:border-slate-700 flex justify-between items-center text-xs text-paleOlive-800 dark:text-paleOlive-400\">\n"
        "                <span class=\"italic\">Hệ Thống Kiểm Soát Vận Hành Kỹ Thuật</span>\n"
        "                <span class=\"font-medium\">BangNC13-TQG</span>\n"
        "            </div>\n"
        "        </div>\n"
        "    </main>\n"
        "\n"
        "    <footer class=\"bg-white dark:bg-slate-800 border-t border-paleOlive-200 dark:border-slate-700 py-4 mt-auto\">\n"
        "        <div class=\"max-w-7xl mx-auto px-4 text-center text-xs text-gray-500 dark:text-gray-400\">\n"
        "            Dashboard Kiểm Soát Ca Tồn & Triển Khai &bull; BangNC13-TQG\n"
        "        </div>\n"
        "    </footer>\n"
        "\n"
        "    <script>\n"
        "        // Global Application State\n"
        "        let activeSheet = \'Ton\'; // \'Ton\' or \'TK\'\n"
        "        let rawDataTon = [];\n"
        "        let rawDataTK = [];\n"
        "        let auditStatuses = {}; // Stores dropdown evaluations key: HĐ\n"
        "\n"
        "        let chart1 = null;\n"
        "        let chart2 = null;\n"
        "        let chart3 = null;\n"
        "        let chart4 = null;\n"
        "\n"
        "        // Toast Notification Display Helper\n"
        "        function showToast(message, type = \'info\') {\n"
        "            const container = document.getElementById(\'toastContainer\');\n"
        "            if (!container) return;\n"
        "\n"
        "            const toast = document.createElement(\'div\');\n"
        "            const bgClass = type === \'success\' ? \'bg-emerald-600\' : type === \'error\' ? \'bg-red-600\' : \'bg-blue-600\';\n"
        "            toast.className = `${bgClass} text-white px-4 py-3 rounded-lg shadow-lg flex items-center gap-2 transition-all transform duration-300 opacity-0 translate-y-2 pointer-events-auto text-xs font-medium`;\n"
        "            toast.innerHTML = `<i class=\"fa-solid ${type === \'success\' ? \'fa-circle-check\' : type === \'error\' ? \'fa-triangle-exclamation\' : \'fa-circle-info\'}\"></i> <span>${message}</span>`;\n"
        "            \n"
        "            container.appendChild(toast);\n"
        "\n"
        "            setTimeout(() => {\n"
        "                toast.classList.remove(\'opacity-0\', \'translate-y-2\');\n"
        "            }, 10);\n"
        "\n"
        "            setTimeout(() => {\n"
        "                toast.classList.add(\'opacity-0\', \'translate-y-2\');\n"
        "                setTimeout(() => toast.remove(), 300);\n"
        "            }, 3500);\n"
        "        }\n"
        "\n"
        "        // Generate Default Mock Data for immediate visual presentation\n"
        "        function initDefaultData() {\n"
        "            rawDataTon = [\n"
        "                { id: \'SGN102931\', customerName: \'Nguyễn Văn A\', block: \'Phuong An Tuong-001- L02\', tonGio: 38, lanHen: 2, clLap: 1, nhanSu: \'TQGTI.KHANHLQ1\', quanLy: \'ANHHV15\', pop: \'TQG01\', ttcl: \'Chờ Xử Lý\', sos: \'SOS\', ghiChu: \'Khách yêu cầu xử lý khẩn\' },\n"
        "                { id: \'SGN102932\', customerName: \'Công Ty Kim Long\', block: \'Xa Nhu Khe-001- L02\', tonGio: 14, lanHen: 1, clLap: 0, nhanSu: \'TQGTI.ANHPH3\', quanLy: \'ANHHV15\', pop: \'TQG02\', ttcl: \'Đang Xử Lý\', sos: \'Support\', ghiChu: \'Khách hẹn chiều nay\' },\n"
        "                { id: \'SGN102933\', customerName: \'Trần Thị C\', block: \'Phuong An Tuong-001- L02\', tonGio: 52, lanHen: 3, clLap: 2, nhanSu: \'TQGTI.BINHLV6\', quanLy: \'QUANLY_B\', pop: \'TQG01\', ttcl: \'Đang XL\', sos: \'SOS\', ghiChu: \'Mất tín hiệu lặp lại\' },\n"
        "                { id: \'SGN102934\', customerName: \'Phạm Minh D\', block: \'Trung Tam-002\', tonGio: 8, lanHen: 1, clLap: 0, nhanSu: \'TQGTI.CAONB\', quanLy: \'QUANLY_B\', pop: \'TQG03\', ttcl: \'Hoàn Thành\', sos: \'Support\', ghiChu: \'Đã bảo trì ONT\' },\n"
        "                { id: \'SGN102935\', customerName: \'Lê Hoàng E\', block: \'Phuong An Tuong-001- L02\', tonGio: 28, lanHen: 2, clLap: 1, nhanSu: \'TQGTI.KHANHLQ1\', quanLy: \'ANHHV15\', pop: \'TQG01\', ttcl: \'Đang XL\', sos: \'Support\', ghiChu: \'Cần hạ dây đấu nối\' }\n"
        "            ];\n"
        "\n"
        "            rawDataTK = [\n"
        "                { id: \'TQAAF1677\', customerName: \'TIN TQG\', block: \'Phuong An Tuong-001- L02\', loaiCV: \'Triển khai mới\', nhanSu: \'TQGTI.KHANHLQ1\', quanLy: \'ANHHV15\', ghiChu: \'Mới kéo cáp\' },\n"
        "                { id: \'TQAAF1851\', customerName: \'TIN TQG\', block: \'Xa Nhu Khe-001- L02\', loaiCV: \'Triển khai mới\', nhanSu: \'TQGTI.KHANHLQ1\', quanLy: \'ANHHV15\', ghiChu: \'Khách báo mai có nhà\' },\n"
        "                { id: \'TQAAF1902\', customerName: \'Công Ty Nam Việt\', block: \'Trung Tam-002\', loaiCV: \'Nâng cấp thiết bị\', nhanSu: \'TQGTI.ANHPH3\', quanLy: \'ANHHV15\', ghiChu: \'Chuyển đổi IP Tĩnh\' },\n"
        "                { id: \'TQAAF2011\', customerName: \'Vũ Thị H\', block: \'Phuong An Tuong-001- L02\', loaiCV: \'Triển khai mới\', nhanSu: \'TQGTI.BINHLV6\', quanLy: \'QUANLY_B\', ghiChu: \'Lắp đợt 2\' }\n"
        "            ];\n"
        "        }\n"
        "\n"
        "        // Handle File Upload & Parse Sheets\n"
        "        function handleFileUpload(e) {\n"
        "            const file = e.target.files[0];\n"
        "            if (!file) return;\n"
        "\n"
        "            const reader = new FileReader();\n"
        "            reader.onload = function(evt) {\n"
        "                try {\n"
        "                    const data = new Uint8Array(evt.target.result);\n"
        "                    const workbook = XLSX.read(data, { type: \'array\' });\n"
        "\n"
        "                    let foundTon = false;\n"
        "                    let foundTK = false;\n"
        "\n"
        "                    workbook.SheetNames.forEach(sheetName => {\n"
        "                        const rawName = sheetName;\n"
        "                        const normalizedName = sheetName.trim().toUpperCase();\n"
        "                        const sheet = workbook.Sheets[sheetName];\n"
        "                        const json = XLSX.utils.sheet_to_json(sheet, { header: 1 });\n"
        "\n"
        "                        // Ưu tiên kiểm tra sheet Bảo Trì: bao gồm cả \" BT\"\n"
        "                        if (rawName.includes(\'BT\') || normalizedName.includes(\'BT\') || normalizedName.includes(\'TỒN\') || normalizedName.includes(\'TON\') || normalizedName.includes(\'BẢO TRÌ\') || normalizedName.includes(\'BAO TRI\') || normalizedName === \'SHEET1\') {\n"
        "                            rawDataTon = parseSheetTon(json);\n"
        "                            foundTon = true;\n"
        "                        } else if (normalizedName === \'TK\' || normalizedName.includes(\'TRIỂN KHAI\') || normalizedName.includes(\'TRIEN KHAI\')) {\n"
        "                            rawDataTK = parseSheetTK(json);\n"
        "                            foundTK = true;\n"
        "                        }\n"
        "                    });\n"
        "\n"
        "                    if (!foundTon && !foundTK && workbook.SheetNames.length > 0) {\n"
        "                        const json = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { header: 1 });\n"
        "                        rawDataTon = parseSheetTon(json);\n"
        "                    }\n"
        "\n"
        "                    showToast(`Tải file thành công! Đã cập nhật dữ liệu.`, \'success\');\n"
        "                    renderDashboard();\n"
        "                } catch (err) {\n"
        "                    console.error(err);\n"
        "                    showToast(\'Lỗi khi đọc file Excel. Vui lòng kiểm tra cấu trúc sheet.\', \'error\');\n"
        "                }\n"
        "            };\n"
        "            reader.readAsArrayBuffer(file);\n"
        "        }\n"
        "\n"
        "        // Parse Sheet Tồn / Bảo Trì (\" BT\")\n"
        "        function parseSheetTon(rows) {\n"
        "            if (!rows || rows.length < 2) return [];\n"
        "\n"
        "            let headerIdx = -1;\n"
        "            let colMap = {};\n"
        "\n"
        "            for (let i = 0; i < Math.min(rows.length, 10); i++) {\n"
        "                const rowStr = (rows[i] || []).map(cell => String(cell || \'\').toUpperCase()).join(\' \');\n"
        "                if (rowStr.includes(\'HĐ\') || rowStr.includes(\'HỢP ĐỒNG\') || rowStr.includes(\'NHÂN SỰ\') || rowStr.includes(\'BLOCK\')) {\n"
        "                    headerIdx = i;\n"
        "                    rows[i].forEach((colName, colIdx) => {\n"
        "                        const name = String(colName || \'\').trim().toUpperCase();\n"
        "                        if (name.includes(\'HĐ\') || name.includes(\'HỢP ĐỒNG\') || name.includes(\'SỐ HĐ\')) colMap.id = colIdx;\n"
        "                        else if (name.includes(\'KHÁCH HÀNG\') || name.includes(\'TEN KH\') || name.includes(\'TÊN KH\')) colMap.customerName = colIdx;\n"
        "                        else if (name.includes(\'BLOCK\')) colMap.block = colIdx;\n"
        "                        else if (name.includes(\'TỒN GIỜ\') || name.includes(\'GIỜ TỒN\') || name.includes(\'TỒN (GIỜ)\')) colMap.tonGio = colIdx;\n"
        "                        else if (name.includes(\'LẦN HẸN\') || name.includes(\'LAN HEN\')) colMap.lanHen = colIdx;\n"
        "                        else if (name.includes(\'LẶP\') || name.includes(\'CL LẶP\')) colMap.clLap = colIdx;\n"
        "                        else if (name.includes(\'NHÂN SỰ\') || name.includes(\'KTV\') || name.includes(\'NHAN SU\')) colMap.nhanSu = colIdx;\n"
        "                        else if (name.includes(\'QUẢN LÝ\') || name.includes(\'QUAN LY\') || name.includes(\'CÁN BỘ\')) colMap.quanLy = colIdx;\n"
        "                        else if (name.includes(\'SOS\') || name.includes(\'MỨC SOS\')) colMap.sos = colIdx;\n"
        "                        else if (name.includes(\'POP\') || name.includes(\'TRẠM\')) colMap.pop = colIdx;\n"
        "                        else if (name.includes(\'TRẠNG THÁI\') || name.includes(\'TTCL\')) colMap.ttcl = colIdx;\n"
        "                        else if (name.includes(\'GHI CHÚ\') || name.includes(\'NOTE\')) colMap.ghiChu = colIdx;\n"
        "                    });\n"
        "                    break;\n"
        "                }\n"
        "            }\n"
        "\n"
        "            const startRow = headerIdx >= 0 ? headerIdx + 1 : 1;\n"
        "            const result = [];\n"
        "\n"
        "            for (let i = startRow; i < rows.length; i++) {\n"
        "                const r = rows[i];\n"
        "                if (!r || r.length === 0) continue;\n"
        "\n"
        "                const id = colMap.id !== undefined ? String(r[colMap.id] || \'\').trim() : (r[5] ? String(r[5]).trim() : (r[2] ? String(r[2]).trim() : \'\'));\n"
        "                if (!id) continue;\n"
        "\n"
        "                const customerName = colMap.customerName !== undefined ? String(r[colMap.customerName] || \'\').trim() : (r[6] ? String(r[6]).trim() : (r[3] ? String(r[3]).trim() : \'\'));\n"
        "                const block = colMap.block !== undefined ? String(r[colMap.block] || \'\').trim() : (r[4] ? String(r[4]).trim() : (r[1] ? String(r[1]).trim() : \'\'));\n"
        "                const tonGioRaw = parseFloat(colMap.tonGio !== undefined ? r[colMap.tonGio] : (r[8] || r[5])) || 0;\n"
        "                const lanHen = parseInt(colMap.lanHen !== undefined ? r[colMap.lanHen] : (r[14] || r[6])) || 1;\n"
        "                const clLap = parseInt(colMap.clLap !== undefined ? r[colMap.clLap] : (r[15] || r[7])) || 0;\n"
        "                const nhanSu = colMap.nhanSu !== undefined ? String(r[colMap.nhanSu] || \'\').trim() : (r[18] ? String(r[18]).trim() : (r[8] ? String(r[8]).trim() : \'\'));\n"
        "                const quanLy = colMap.quanLy !== undefined ? String(r[colMap.quanLy] || \'\').trim() : (r[39] ? String(r[39]).trim() : (r[14] ? String(r[14]).trim() : \'\'));\n"
        "                const sosRaw = colMap.sos !== undefined ? String(r[colMap.sos] || \'\').trim() : (r[26] ? String(r[26]).trim() : (r[10] ? String(r[10]).trim() : \'\'));\n"
        "                const pop = colMap.pop !== undefined ? String(r[colMap.pop] || \'\').trim() : (r[28] ? String(r[28]).trim() : (r[11] ? String(r[11]).trim() : \'\'));\n"
        "                const ttcl = colMap.ttcl !== undefined ? String(r[colMap.ttcl] || \'\').trim() : (r[19] ? String(r[19]).trim() : (r[9] ? String(r[9]).trim() : \'Đang XL\'));\n"
        "                const ghiChu = colMap.ghiChu !== undefined ? String(r[colMap.ghiChu] || \'\').trim() : (r[38] ? String(r[38]).trim() : (r[22] ? String(r[22]).trim() : \'\'));\n"
        "\n"
        "                result.push({\n"
        "                    id, customerName, block,\n"
        "                    tonGio: tonGioRaw,\n"
        "                    lanHen, clLap, nhanSu, quanLy, pop, ttcl,\n"
        "                    sos: sosRaw.toUpperCase().includes(\'SOS\') ? \'SOS\' : \'Support\',\n"
        "                    ghiChu\n"
        "                });\n"
        "            }\n"
        "            return result;\n"
        "        }\n"
        "\n"
        "        // Parse Sheet TK\n"
        "        function parseSheetTK(rows) {\n"
        "            if (!rows || rows.length < 2) return [];\n"
        "\n"
        "            let headerIdx = -1;\n"
        "            let colMap = {};\n"
        "\n"
        "            for (let i = 0; i < Math.min(rows.length, 10); i++) {\n"
        "                const rowStr = (rows[i] || []).map(cell => String(cell || \'\').toUpperCase()).join(\' \');\n"
        "                if (rowStr.includes(\'HĐ\') || rowStr.includes(\'HỢP ĐỒNG\') || rowStr.includes(\'NHÂN SỰ\') || rowStr.includes(\'BLOCK\')) {\n"
        "                    headerIdx = i;\n"
        "                    rows[i].forEach((colName, colIdx) => {\n"
        "                        const name = String(colName || \'\').trim().toUpperCase();\n"
        "                        if (name.includes(\'HĐ\') || name.includes(\'HỢP ĐỒNG\') || name.includes(\'SỐ HĐ\')) colMap.id = colIdx;\n"
        "                        else if (name.includes(\'KHÁCH HÀNG\') || name.includes(\'TEN KH\') || name.includes(\'TÊN KH\')) colMap.customerName = colIdx;\n"
        "                        else if (name.includes(\'BLOCK\')) colMap.block = colIdx;\n"
        "                        else if (name.includes(\'LOẠI\') || name.includes(\'CÔNG VIỆC\') || name.includes(\'LOAI CV\')) colMap.loaiCV = colIdx;\n"
        "                        else if (name.includes(\'NHÂN SỰ\') || name.includes(\'KTV\') || name.includes(\'NHAN SU\')) colMap.nhanSu = colIdx;\n"
        "                        else if (name.includes(\'QUẢN LÝ\') || name.includes(\'QUAN LY\') || name.includes(\'CÁN BỘ\')) colMap.quanLy = colIdx;\n"
        "                        else if (name.includes(\'GHI CHÚ\') || name.includes(\'NOTE\')) colMap.ghiChu = colIdx;\n"
        "                    });\n"
        "                    break;\n"
        "                }\n"
        "            }\n"
        "\n"
        "            const startRow = headerIdx >= 0 ? headerIdx + 1 : 1;\n"
        "            const result = [];\n"
        "\n"
        "            for (let i = startRow; i < rows.length; i++) {\n"
        "                const r = rows[i];\n"
        "                if (!r || r.length === 0) continue;\n"
        "\n"
        "                const id = colMap.id !== undefined ? String(r[colMap.id] || \'\').trim() : String(r[3] || \'\').trim();\n"
        "                if (!id) continue;\n"
        "\n"
        "                const customerName = colMap.customerName !== undefined ? String(r[colMap.customerName] || \'\').trim() : String(r[4] || \'\').trim();\n"
        "                const block = colMap.block !== undefined ? String(r[colMap.block] || \'\').trim() : String(r[5] || \'\').trim();\n"
        "                const loaiCV = colMap.loaiCV !== undefined ? String(r[colMap.loaiCV] || \'\').trim() : (r[12] ? String(r[12]).trim() : \'Triển khai mới\');\n"
        "                const nhanSu = colMap.nhanSu !== undefined ? String(r[colMap.nhanSu] || \'\').trim() : String(r[17] || \'\').trim();\n"
        "                const quanLy = colMap.quanLy !== undefined ? String(r[colMap.quanLy] || \'\').trim() : String(r[22] || \'\').trim();\n"
        "                const ghiChu = colMap.ghiChu !== undefined ? String(r[colMap.ghiChu] || \'\').trim() : String(r[21] || \'\').trim();\n"
        "\n"
        "                result.push({ id, customerName, block, loaiCV, nhanSu, quanLy, ghiChu });\n"
        "            }\n"
        "            return result;\n"
        "        }\n"
        "\n"
        "        // Switch Active Sheet\n"
        "        function switchSheet(sheetType) {\n"
        "            activeSheet = sheetType;\n"
        "\n"
        "            const btnTon = document.getElementById(\'btnSheetTon\');\n"
        "            const btnTK = document.getElementById(\'btnSheetTK\');\n"
        "            const bannerTitle = document.getElementById(\'bannerTitle\');\n"
        "            const tableTitle = document.getElementById(\'tableTitle\');\n"
        "\n"
        "            if (sheetType === \'Ton\') {\n"
        "                btnTon.className = \"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 bg-paleOlive-500 text-white shadow-sm\";\n"
        "                btnTK.className = \"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 text-paleOlive-800 dark:text-paleOlive-200 hover:bg-paleOlive-200/60 dark:hover:bg-slate-600\";\n"
        "                \n"
        "                bannerTitle.innerText = \"Các trường thông tin kiểm soát trọng yếu (Bảo Trì):\";\n"
        "                tableTitle.innerText = \"BẢNG KIỂM SOÁT DỮ LIỆU TỒN CA (BẢO TRÌ)\";\n"
        "            } else {\n"
        "                btnTK.className = \"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 bg-paleOlive-500 text-white shadow-sm\";\n"
        "                btnTon.className = \"px-3 sm:px-5 py-2 rounded-lg text-xs sm:text-sm font-semibold transition-all flex items-center gap-2 text-paleOlive-800 dark:text-paleOlive-200 hover:bg-paleOlive-200/60 dark:hover:bg-slate-600\";\n"
        "                \n"
        "                bannerTitle.innerText = \"Các trường thông tin kiểm soát trọng yếu (Triển Khai):\";\n"
        "                tableTitle.innerText = \"BẢNG KIỂM SOÁT DỮ LIỆU TRIỂN KHAI (TK)\";\n"
        "            }\n"
        "\n"
        "            renderDashboard();\n"
        "        }\n"
        "\n"
        "        // Render Dashboard KPI Cards\n"
        "        function renderKPIs() {\n"
        "            const container = document.getElementById(\'kpiContainer\');\n"
        "            const data = activeSheet === \'Ton\' ? rawDataTon : rawDataTK;\n"
        "\n"
        "            document.getElementById(\'recordCountBadge\').innerText = data.length;\n"
        "\n"
        "            if (activeSheet === \'Ton\') {\n"
        "                const total = data.length;\n"
        "                const sosCount = data.filter(d => d.sos === \'SOS\').length;\n"
        "                const lapCount = data.filter(d => d.clLap > 0).length;\n"
        "                const henCount = data.filter(d => d.lanHen > 1).length;\n"
        "                const tonOver24 = data.filter(d => d.tonGio >= 24).length;\n"
        "                const checkedCount = data.filter(d => auditStatuses[d.id] && auditStatuses[d.id] !== \'\').length;\n"
        "\n"
        "                container.innerHTML = `\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-paleOlive-700 dark:text-paleOlive-400 font-semibold uppercase\">Tổng ca tồn</span>\n"
        "                        <div class=\"text-2xl font-bold text-gray-900 dark:text-white my-1\">${total}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Tất cả hợp đồng</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-red-600 dark:text-red-400 font-semibold uppercase\">Mức SOS</span>\n"
        "                        <div class=\"text-2xl font-bold text-red-600 dark:text-red-400 my-1\">${sosCount}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Ưu tiên xử lý</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-amber-600 dark:text-amber-400 font-semibold uppercase\">CL Lặp > 0</span>\n"
        "                        <div class=\"text-2xl font-bold text-amber-600 dark:text-amber-400 my-1\">${lapCount}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Bị lặp chất lượng</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-purple-600 dark:text-purple-400 font-semibold uppercase\">Đã hẹn > 1 lần</span>\n"
        "                        <div class=\"text-2xl font-bold text-purple-600 dark:text-purple-400 my-1\">${henCount}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Trễ hẹn nhiều lần</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-rose-600 dark:text-rose-400 font-semibold uppercase\">Tồn > 24 Giờ</span>\n"
        "                        <div class=\"text-2xl font-bold text-rose-600 dark:text-rose-400 my-1\">${tonOver24}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Vượt SLA tiêu chuẩn</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between\">\n"
        "                        <span class=\"text-xs text-emerald-600 dark:text-emerald-400 font-semibold uppercase\">Đã Kiểm Soát</span>\n"
        "                        <div class=\"text-2xl font-bold text-emerald-600 dark:text-emerald-400 my-1\">${checkedCount}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Đã đánh giá status</span>\n"
        "                    </div>\n"
        "                `;\n"
        "            } else {\n"
        "                const total = data.length;\n"
        "                const newTK = data.filter(d => d.loaiCV.toLowerCase().includes(\'mới\')).length;\n"
        "                const upgradeTK = data.filter(d => d.loaiCV.toLowerCase().includes(\'nâng\') || d.loaiCV.toLowerCase().includes(\'chuyển\')).length;\n"
        "\n"
        "                container.innerHTML = `\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between sm:col-span-2\">\n"
        "                        <span class=\"text-xs text-paleOlive-700 dark:text-paleOlive-400 font-semibold uppercase\">Tổng ca triển khai</span>\n"
        "                        <div class=\"text-2xl font-bold text-gray-900 dark:text-white my-1\">${total}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Số lượng hợp đồng triển khai</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between sm:col-span-2\">\n"
        "                        <span class=\"text-xs text-blue-600 dark:text-blue-400 font-semibold uppercase\">Ca Triển Khai Mới</span>\n"
        "                        <div class=\"text-2xl font-bold text-blue-600 dark:text-blue-400 my-1\">${newTK}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Công việc lắp mới</span>\n"
        "                    </div>\n"
        "                    <div class=\"bg-white dark:bg-slate-800 p-3 sm:p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm flex flex-col justify-between sm:col-span-2\">\n"
        "                        <span class=\"text-xs text-purple-600 dark:text-purple-400 font-semibold uppercase\">Nâng cấp / Chuyển điểm</span>\n"
        "                        <div class=\"text-2xl font-bold text-purple-600 dark:text-purple-400 my-1\">${upgradeTK}</div>\n"
        "                        <span class=\"text-[10px] text-gray-500 dark:text-gray-400\">Dịch vụ bổ sung</span>\n"
        "                    </div>\n"
        "                `;\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Render Dynamic Controls Filters\n"
        "        function renderFilters() {\n"
        "            const container = document.getElementById(\'filterInputsGroup\');\n"
        "            const data = activeSheet === \'Ton\' ? rawDataTon : rawDataTK;\n"
        "\n"
        "            const quanLyList = [...new Set(data.map(d => d.quanLy).filter(Boolean))].sort();\n"
        "            const blockList = [...new Set(data.map(d => d.block).filter(Boolean))].sort();\n"
        "\n"
        "            if (activeSheet === \'Ton\') {\n"
        "                container.innerHTML = `\n"
        "                    <div class=\"relative\">\n"
        "                        <i class=\"fa-solid fa-magnifying-glass absolute left-3 top-2.5 text-gray-400 text-xs\"></i>\n"
        "                        <input type=\"text\" id=\"filterSearch\" oninput=\"applyFiltersAndRenderTable()\" placeholder=\"Tìm Số HĐ, Tên KH, Ghi chú...\" class=\"w-full pl-8 pr-3 py-1.5 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 focus:border-paleOlive-500 border dark:text-white\">\n"
        "                    </div>\n"
        "                    \n"
        "                    <select id=\"filterQuanLy\" onchange=\"onQuanLyChange()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border font-semibold text-paleOlive-900 dark:text-paleOlive-200\">\n"
        "                        <option value=\"\">Tất cả Quản lý</option>\n"
        "                        ${quanLyList.map(q => `<option value=\"${q}\">${q}</option>`).join(\'\')}\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterNhanSu\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Nhân sự</option>\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterSOS\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Mức SOS</option>\n"
        "                        <option value=\"SOS\">Chỉ lấy: SOS</option>\n"
        "                        <option value=\"Support\">Chỉ lấy: Support</option>\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterRepeat\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả CL Lặp</option>\n"
        "                        <option value=\"NON_ZERO\">Chỉ khác 0 (Lặp > 0)</option>\n"
        "                        <option value=\"0\">Bằng 0 (= 0)</option>\n"
        "                        <option value=\"1\">Lặp 1 lần</option>\n"
        "                        <option value=\"2\">Lặp 2 lần</option>\n"
        "                        <option value=\"3\">Lặp ≥ 3 lần</option>\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterBlock\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Block</option>\n"
        "                        ${blockList.map(b => `<option value=\"${b}\">${b}</option>`).join(\'\')}\n"
        "                    </select>\n"
        "                `;\n"
        "            } else {\n"
        "                const loaiCVList = [...new Set(data.map(d => d.loaiCV).filter(Boolean))].sort();\n"
        "\n"
        "                container.innerHTML = `\n"
        "                    <div class=\"relative sm:col-span-2\">\n"
        "                        <i class=\"fa-solid fa-magnifying-glass absolute left-3 top-2.5 text-gray-400 text-xs\"></i>\n"
        "                        <input type=\"text\" id=\"filterSearch\" oninput=\"applyFiltersAndRenderTable()\" placeholder=\"Tìm Số HĐ, Tên KH, Ghi chú...\" class=\"w-full pl-8 pr-3 py-1.5 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                    </div>\n"
        "\n"
        "                    <select id=\"filterLoaiCV\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Loại CV</option>\n"
        "                        ${loaiCVList.map(l => `<option value=\"${l}\">${l}</option>`).join(\'\')}\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterQuanLy\" onchange=\"onQuanLyChange()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border font-semibold text-paleOlive-900 dark:text-paleOlive-200\">\n"
        "                        <option value=\"\">Tất cả Quản lý</option>\n"
        "                        ${quanLyList.map(q => `<option value=\"${q}\">${q}</option>`).join(\'\')}\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterNhanSu\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Nhân sự</option>\n"
        "                    </select>\n"
        "\n"
        "                    <select id=\"filterBlock\" onchange=\"applyFiltersAndRenderTable()\" class=\"w-full py-1.5 px-3 text-xs rounded-lg border-paleOlive-200 dark:border-slate-600 dark:bg-slate-900 focus:ring-paleOlive-500 border dark:text-white\">\n"
        "                        <option value=\"\">Tất cả Block</option>\n"
        "                        ${blockList.map(b => `<option value=\"${b}\">${b}</option>`).join(\'\')}\n"
        "                    </select>\n"
        "                `;\n"
        "            }\n"
        "\n"
        "            // Tự động cập nhật danh sách Nhân sự theo Quản lý đã chọn\n"
        "            updateNhanSuDropdown();\n"
        "        }\n"
        "\n"
        "        // Event handler when Manager dropdown changes\n"
        "        function onQuanLyChange() {\n"
        "            updateNhanSuDropdown();\n"
        "            applyFiltersAndRenderTable();\n"
        "        }\n"
        "\n"
        "        // Dynamically update Staff dropdown based on current selected Manager\n"
        "        function updateNhanSuDropdown() {\n"
        "            const data = activeSheet === \'Ton\' ? rawDataTon : rawDataTK;\n"
        "            const quanLyVal = document.getElementById(\'filterQuanLy\')?.value || \'\';\n"
        "            const selectNhanSu = document.getElementById(\'filterNhanSu\');\n"
        "            if (!selectNhanSu) return;\n"
        "\n"
        "            const currentSelectedNhanSu = selectNhanSu.value;\n"
        "\n"
        "            // Filter relevant data by manager if selected\n"
        "            const relevantData = quanLyVal ? data.filter(d => d.quanLy === quanLyVal) : data;\n"
        "            const nhanSuList = [...new Set(relevantData.map(d => d.nhanSu).filter(Boolean))].sort();\n"
        "\n"
        "            selectNhanSu.innerHTML = `<option value=\"\">Tất cả Nhân sự</option>` + \n"
        "                nhanSuList.map(s => `<option value=\"${s}\">${s}</option>`).join(\'\');\n"
        "\n"
        "            // Keep existing selection if still available in new filtered list\n"
        "            if (nhanSuList.includes(currentSelectedNhanSu)) {\n"
        "                selectNhanSu.value = currentSelectedNhanSu;\n"
        "            } else {\n"
        "                selectNhanSu.value = \'\';\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Filter Data & Render Both Table and Charts\n"
        "        function applyFiltersAndRenderTable() {\n"
        "            const data = activeSheet === \'Ton\' ? rawDataTon : rawDataTK;\n"
        "            const searchVal = document.getElementById(\'filterSearch\')?.value.toLowerCase() || \'\';\n"
        "            const quanLyVal = document.getElementById(\'filterQuanLy\')?.value || \'\';\n"
        "            const nhanSuVal = document.getElementById(\'filterNhanSu\')?.value || \'\';\n"
        "            const blockVal = document.getElementById(\'filterBlock\')?.value || \'\';\n"
        "\n"
        "            let filtered = data.filter(item => {\n"
        "                const matchSearch = !searchVal || \n"
        "                    (item.id && item.id.toLowerCase().includes(searchVal)) ||\n"
        "                    (item.customerName && item.customerName.toLowerCase().includes(searchVal)) ||\n"
        "                    (item.ghiChu && item.ghiChu.toLowerCase().includes(searchVal));\n"
        "\n"
        "                const matchQuanLy = !quanLyVal || item.quanLy === quanLyVal;\n"
        "                const matchNhanSu = !nhanSuVal || item.nhanSu === nhanSuVal;\n"
        "                const matchBlock = !blockVal || item.block === blockVal;\n"
        "\n"
        "                if (activeSheet === \'Ton\') {\n"
        "                    const sosVal = document.getElementById(\'filterSOS\')?.value || \'\';\n"
        "                    const repeatVal = document.getElementById(\'filterRepeat\')?.value || \'\';\n"
        "\n"
        "                    const matchSOS = !sosVal || item.sos === sosVal;\n"
        "                    let matchRepeat = true;\n"
        "\n"
        "                    if (repeatVal === \'NON_ZERO\') matchRepeat = item.clLap > 0;\n"
        "                    else if (repeatVal === \'0\') matchRepeat = item.clLap === 0;\n"
        "                    else if (repeatVal === \'1\') matchRepeat = item.clLap === 1;\n"
        "                    else if (repeatVal === \'2\') matchRepeat = item.clLap === 2;\n"
        "                    else if (repeatVal === \'3\') matchRepeat = item.clLap >= 3;\n"
        "\n"
        "                    return matchSearch && matchQuanLy && matchNhanSu && matchBlock && matchSOS && matchRepeat;\n"
        "                } else {\n"
        "                    const loaiCVVal = document.getElementById(\'filterLoaiCV\')?.value || \'\';\n"
        "                    const matchLoaiCV = !loaiCVVal || item.loaiCV === loaiCVVal;\n"
        "\n"
        "                    return matchSearch && matchQuanLy && matchNhanSu && matchBlock && matchLoaiCV;\n"
        "                }\n"
        "            });\n"
        "\n"
        "            document.getElementById(\'displayedCount\').innerText = filtered.length;\n"
        "            document.getElementById(\'totalCount\').innerText = data.length;\n"
        "\n"
        "            renderTableHead();\n"
        "            renderTableBody(filtered);\n"
        "            renderCharts(filtered);\n"
        "        }\n"
        "\n"
        "        // Clear All Filter Inputs\n"
        "        function resetFilters() {\n"
        "            renderFilters();\n"
        "            applyFiltersAndRenderTable();\n"
        "        }\n"
        "\n"
        "        // Render Table Header Columns\n"
        "        function renderTableHead() {\n"
        "            const head = document.getElementById(\'tableHeader\');\n"
        "            if (activeSheet === \'Ton\') {\n"
        "                head.innerHTML = `\n"
        "                    <tr>\n"
        "                        <th class=\"py-3 px-3 w-12 text-center\">STT</th>\n"
        "                        <th class=\"py-3 px-3\">SỐ HĐ</th>\n"
        "                        <th class=\"py-3 px-3\">KHÁCH HÀNG</th>\n"
        "                        <th class=\"py-3 px-3\">BLOCK</th>\n"
        "                        <th class=\"py-3 px-3 text-center\">MỨC SOS</th>\n"
        "                        <th class=\"py-3 px-3 text-center\">TỒN GIỜ</th>\n"
        "                        <th class=\"py-3 px-3 text-center\">LẦN HẸN</th>\n"
        "                        <th class=\"py-3 px-3 text-center\">CL LẶP</th>\n"
        "                        <th class=\"py-3 px-3\">NHÂN SỰ</th>\n"
        "                        <th class=\"py-3 px-3\">QUẢN LÝ</th>\n"
        "                        <th class=\"py-3 px-3 min-w-[140px]\">KIỂM SOÁT</th>\n"
        "                        <th class=\"py-3 px-3\">GHI CHÚ CHI TIẾT</th>\n"
        "                    </tr>\n"
        "                `;\n"
        "            } else {\n"
        "                head.innerHTML = `\n"
        "                    <tr>\n"
        "                        <th class=\"py-3 px-3 w-12 text-center\">STT</th>\n"
        "                        <th class=\"py-3 px-3\">SỐ HĐ</th>\n"
        "                        <th class=\"py-3 px-3\">KHÁCH HÀNG</th>\n"
        "                        <th class=\"py-3 px-3\">BLOCK</th>\n"
        "                        <th class=\"py-3 px-3\">LOẠI HÌNH / CV</th>\n"
        "                        <th class=\"py-3 px-3\">NHÂN SỰ</th>\n"
        "                        <th class=\"py-3 px-3\">QUẢN LÝ</th>\n"
        "                        <th class=\"py-3 px-3\">GHI CHÚ CHI TIẾT</th>\n"
        "                    </tr>\n"
        "                `;\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Render Rows in Data Table\n"
        "        function renderTableBody(data) {\n"
        "            const body = document.getElementById(\'tableBody\');\n"
        "            if (!data || data.length === 0) {\n"
        "                body.innerHTML = `\n"
        "                    <tr>\n"
        "                        <td colspan=\"12\" class=\"py-8 text-center text-gray-400 italic\">\n"
        "                            Không tìm thấy dữ liệu phù hợp với bộ lọc hiện tại.\n"
        "                        </td>\n"
        "                    </tr>\n"
        "                `;\n"
        "                return;\n"
        "            }\n"
        "\n"
        "            let html = \'\';\n"
        "            data.forEach((item, index) => {\n"
        "                if (activeSheet === \'Ton\') {\n"
        "                    const currentStatus = auditStatuses[item.id] || \'\';\n"
        "                    const sosBadge = item.sos === \'SOS\' \n"
        "                        ? `<span class=\"bg-red-100 text-red-800 dark:bg-red-900/60 dark:text-red-300 font-bold px-2 py-0.5 rounded text-[10px]\">SOS</span>` \n"
        "                        : `<span class=\"bg-gray-100 text-gray-700 dark:bg-slate-700 dark:text-gray-300 px-2 py-0.5 rounded text-[10px]\">Support</span>`;\n"
        "                    \n"
        "                    const lapBadge = item.clLap > 0 \n"
        "                        ? `<span class=\"text-amber-600 dark:text-amber-400 font-bold\">${item.clLap}</span>` \n"
        "                        : `<span class=\"text-gray-400\">0</span>`;\n"
        "\n"
        "                    const tonGioBadge = item.tonGio >= 24 \n"
        "                        ? `<span class=\"text-rose-600 dark:text-rose-400 font-bold\">${item.tonGio}h</span>`\n"
        "                        : `<span>${item.tonGio}h</span>`;\n"
        "\n"
        "                    html += `\n"
        "                        <tr class=\"hover:bg-paleOlive-100/50 dark:hover:bg-slate-800 transition\">\n"
        "                            <td class=\"py-2.5 px-3 text-center font-medium text-gray-500\">${index + 1}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-bold text-paleOlive-900 dark:text-paleOlive-200\">${item.id}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-medium\">${item.customerName || \'N/A\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-gray-600 dark:text-gray-400 text-[11px]\">${item.block || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-center\">${sosBadge}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-center\">${tonGioBadge}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-center font-semibold\">${item.lanHen}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-center\">${lapBadge}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-medium text-paleOlive-800 dark:text-paleOlive-300\">${item.nhanSu || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-semibold text-gray-800 dark:text-gray-200\">${item.quanLy || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 col-highlight\">\n"
        "                                <select onchange=\"updateAuditStatus(\'${item.id}\', this.value)\" class=\"w-full text-xs py-1 px-2 rounded border-paleOlive-300 dark:border-slate-600 bg-white dark:bg-slate-800 focus:ring-1 focus:ring-paleOlive-500\">\n"
        "                                    <option value=\"\" ${currentStatus === \'\' ? \'selected\' : \'\'}>-- Chọn --</option>\n"
        "                                    <option value=\"Đã duyệt\" ${currentStatus === \'Đã duyệt\' ? \'selected\' : \'\'}>Đã duyệt</option>\n"
        "                                    <option value=\"Chờ đôn đốc\" ${currentStatus === \'Chờ đôn đốc\' ? \'selected\' : \'\'}>Chờ đôn đốc</option>\n"
        "                                    <option value=\"Cần điều phối lại\" ${currentStatus === \'Cần điều phối lại\' ? \'selected\' : \'\'}>Cần điều phối lại</option>\n"
        "                                    <option value=\"Cần KTV giải trình\" ${currentStatus === \'Cần KTV giải trình\' ? \'selected\' : \'\'}>Cần KTV giải trình</option>\n"
        "                                </select>\n"
        "                            </td>\n"
        "                            <td class=\"py-2.5 px-3 text-gray-600 dark:text-gray-400 max-w-xs truncate\" title=\"${item.ghiChu || \'\'}\">${item.ghiChu || \'-\'}</td>\n"
        "                        </tr>\n"
        "                    `;\n"
        "                } else {\n"
        "                    html += `\n"
        "                        <tr class=\"hover:bg-paleOlive-100/50 dark:hover:bg-slate-800 transition\">\n"
        "                            <td class=\"py-2.5 px-3 text-center font-medium text-gray-500\">${index + 1}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-bold text-paleOlive-900 dark:text-paleOlive-200\">${item.id}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-medium\">${item.customerName || \'N/A\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-gray-600 dark:text-gray-400 text-[11px]\">${item.block || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3\"><span class=\"bg-paleOlive-100 dark:bg-paleOlive-900/50 text-paleOlive-800 dark:text-paleOlive-300 px-2 py-0.5 rounded font-medium\">${item.loaiCV || \'Triển khai\'}</span></td>\n"
        "                            <td class=\"py-2.5 px-3 font-medium text-paleOlive-800 dark:text-paleOlive-300\">${item.nhanSu || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 font-semibold text-gray-800 dark:text-gray-200\">${item.quanLy || \'-\'}</td>\n"
        "                            <td class=\"py-2.5 px-3 text-gray-600 dark:text-gray-400 max-w-xs truncate\" title=\"${item.ghiChu || \'\'}\">${item.ghiChu || \'-\'}</td>\n"
        "                        </tr>\n"
        "                    `;\n"
        "                }\n"
        "            });\n"
        "\n"
        "            body.innerHTML = html;\n"
        "        }\n"
        "\n"
        "        // Save status modification\n"
        "        function updateAuditStatus(id, val) {\n"
        "            auditStatuses[id] = val;\n"
        "            renderKPIs();\n"
        "            showToast(`Cập nhật trạng thái kiểm soát HĐ ${id}: ${val || \'Xóa chọn\'}`, \'info\');\n"
        "        }\n"
        "\n"
        "        // Render Interactive Analytics Charts using Chart.js\n"
        "        function renderCharts(filteredData) {\n"
        "            const container = document.getElementById(\'chartsGrid\');\n"
        "            container.innerHTML = `\n"
        "                <div class=\"bg-white dark:bg-slate-800 p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm\">\n"
        "                    <h3 class=\"text-xs font-bold text-gray-700 dark:text-gray-200 mb-3 uppercase flex items-center gap-1.5\">\n"
        "                        <i class=\"fa-solid fa-chart-bar text-paleOlive-600\"></i> Top 10 Nhân Sự Lớn Nhất\n"
        "                    </h3>\n"
        "                    <div class=\"h-48\">\n"
        "                        <canvas id=\"chartNhanSu\"></canvas>\n"
        "                    </div>\n"
        "                </div>\n"
        "\n"
        "                <div class=\"bg-white dark:bg-slate-800 p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm\">\n"
        "                    <h3 class=\"text-xs font-bold text-gray-700 dark:text-gray-200 mb-3 uppercase flex items-center gap-1.5\">\n"
        "                        <i class=\"fa-solid fa-user-tie text-paleOlive-600\"></i> Phân Bổ Theo Quản Lý\n"
        "                    </h3>\n"
        "                    <div class=\"h-48\">\n"
        "                        <canvas id=\"chartQuanLy\"></canvas>\n"
        "                    </div>\n"
        "                </div>\n"
        "\n"
        "                <div class=\"bg-white dark:bg-slate-800 p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm\">\n"
        "                    <h3 class=\"text-xs font-bold text-gray-700 dark:text-gray-200 mb-3 uppercase flex items-center gap-1.5\">\n"
        "                        <i class=\"fa-solid fa-cubes text-paleOlive-600\"></i> Phân Bổ Theo Block\n"
        "                    </h3>\n"
        "                    <div class=\"h-48\">\n"
        "                        <canvas id=\"chartBlock\"></canvas>\n"
        "                    </div>\n"
        "                </div>\n"
        "\n"
        "                <div class=\"bg-white dark:bg-slate-800 p-4 rounded-xl border border-paleOlive-200 dark:border-slate-700 shadow-sm\">\n"
        "                    <h3 class=\"text-xs font-bold text-gray-700 dark:text-gray-200 mb-3 uppercase flex items-center gap-1.5\">\n"
        "                        <i class=\"fa-solid fa-chart-pie text-paleOlive-600\"></i> ${activeSheet === \'Ton\' ? \'Tỷ Lệ Mức SOS\' : \'Phân Loại Công Việc\'}\n"
        "                    </h3>\n"
        "                    <div class=\"h-48\">\n"
        "                        <canvas id=\"chartPie\"></canvas>\n"
        "                    </div>\n"
        "                </div>\n"
        "            `;\n"
        "\n"
        "            // Destroy existing instances if any\n"
        "            if (chart1) chart1.destroy();\n"
        "            if (chart2) chart2.destroy();\n"
        "            if (chart3) chart3.destroy();\n"
        "            if (chart4) chart4.destroy();\n"
        "\n"
        "            const isDark = document.documentElement.classList.contains(\'dark\');\n"
        "            const textColor = isDark ? \'#cbd5e1\' : \'#475569\';\n"
        "\n"
        "            // Chart 1: Top Staff\n"
        "            const nsCounts = {};\n"
        "            filteredData.forEach(d => { if (d.nhanSu) nsCounts[d.nhanSu] = (nsCounts[d.nhanSu] || 0) + 1; });\n"
        "            const topNS = Object.entries(nsCounts).sort((a,b) => b[1] - a[1]).slice(0, 10);\n"
        "\n"
        "            chart1 = new Chart(document.getElementById(\'chartNhanSu\'), {\n"
        "                type: \'bar\',\n"
        "                data: {\n"
        "                    labels: topNS.map(x => x[0]),\n"
        "                    datasets: [{\n"
        "                        data: topNS.map(x => x[1]),\n"
        "                        backgroundColor: \'#94b36c\',\n"
        "                        borderRadius: 4\n"
        "                    }]\n"
        "                },\n"
        "                options: {\n"
        "                    responsive: true,\n"
        "                    maintainAspectRatio: false,\n"
        "                    plugins: { legend: { display: false } },\n"
        "                    scales: {\n"
        "                        x: { ticks: { color: textColor, font: { size: 9 } } },\n"
        "                        y: { ticks: { color: textColor, stepSize: 1 } }\n"
        "                    }\n"
        "                }\n"
        "            });\n"
        "\n"
        "            // Chart 2: Quản Lý\n"
        "            const qlCounts = {};\n"
        "            filteredData.forEach(d => { if (d.quanLy) qlCounts[d.quanLy] = (qlCounts[d.quanLy] || 0) + 1; });\n"
        "            const topQL = Object.entries(qlCounts).sort((a,b) => b[1] - a[1]);\n"
        "\n"
        "            chart2 = new Chart(document.getElementById(\'chartQuanLy\'), {\n"
        "                type: \'bar\',\n"
        "                data: {\n"
        "                    labels: topQL.map(x => x[0]),\n"
        "                    datasets: [{\n"
        "                        data: topQL.map(x => x[1]),\n"
        "                        backgroundColor: \'#759948\',\n"
        "                        borderRadius: 4\n"
        "                    }]\n"
        "                },\n"
        "                options: {\n"
        "                    responsive: true,\n"
        "                    maintainAspectRatio: false,\n"
        "                    plugins: { legend: { display: false } },\n"
        "                    scales: {\n"
        "                        x: { ticks: { color: textColor, font: { size: 9 } } },\n"
        "                        y: { ticks: { color: textColor, stepSize: 1 } }\n"
        "                    }\n"
        "                }\n"
        "            });\n"
        "\n"
        "            // Chart 3: Block\n"
        "            const blkCounts = {};\n"
        "            filteredData.forEach(d => { if (d.block) blkCounts[d.block] = (blkCounts[d.block] || 0) + 1; });\n"
        "            const topBLK = Object.entries(blkCounts).sort((a,b) => b[1] - a[1]).slice(0, 5);\n"
        "\n"
        "            chart3 = new Chart(document.getElementById(\'chartBlock\'), {\n"
        "                type: \'bar\',\n"
        "                data: {\n"
        "                    labels: topBLK.map(x => x[0]),\n"
        "                    datasets: [{\n"
        "                        data: topBLK.map(x => x[1]),\n"
        "                        backgroundColor: \'#5c7b35\',\n"
        "                        borderRadius: 4\n"
        "                    }]\n"
        "                },\n"
        "                options: {\n"
        "                    responsive: true,\n"
        "                    maintainAspectRatio: false,\n"
        "                    plugins: { legend: { display: false } },\n"
        "                    scales: {\n"
        "                        x: { ticks: { color: textColor, font: { size: 8 } } },\n"
        "                        y: { ticks: { color: textColor, stepSize: 1 } }\n"
        "                    }\n"
        "                }\n"
        "            });\n"
        "\n"
        "            // Chart 4: Pie Chart (SOS or LoaiCV)\n"
        "            if (activeSheet === \'Ton\') {\n"
        "                const sosCounts = { \'SOS\': 0, \'Support\': 0 };\n"
        "                filteredData.forEach(d => { sosCounts[d.sos] = (sosCounts[d.sos] || 0) + 1; });\n"
        "\n"
        "                chart4 = new Chart(document.getElementById(\'chartPie\'), {\n"
        "                    type: \'doughnut\',\n"
        "                    data: {\n"
        "                        labels: [\'SOS\', \'Support\'],\n"
        "                        datasets: [{\n"
        "                            data: [sosCounts[\'SOS\'], sosCounts[\'Support\']],\n"
        "                            backgroundColor: [\'#ef4444\', \'#94b36c\']\n"
        "                        }]\n"
        "                    },\n"
        "                    options: {\n"
        "                        responsive: true,\n"
        "                        maintainAspectRatio: false,\n"
        "                        plugins: { legend: { labels: { color: textColor, font: { size: 10 } } } }\n"
        "                    }\n"
        "                });\n"
        "            } else {\n"
        "                const cvCounts = {};\n"
        "                filteredData.forEach(d => { cvCounts[d.loaiCV] = (cvCounts[d.loaiCV] || 0) + 1; });\n"
        "\n"
        "                chart4 = new Chart(document.getElementById(\'chartPie\'), {\n"
        "                    type: \'doughnut\',\n"
        "                    data: {\n"
        "                        labels: Object.keys(cvCounts),\n"
        "                        datasets: [{\n"
        "                            data: Object.values(cvCounts),\n"
        "                            backgroundColor: [\'#3b82f6\', \'#8b5cf6\', \'#ec4899\', \'#10b981\']\n"
        "                        }]\n"
        "                    },\n"
        "                    options: {\n"
        "                        responsive: true,\n"
        "                        maintainAspectRatio: false,\n"
        "                        plugins: { legend: { labels: { color: textColor, font: { size: 10 } } } }\n"
        "                    }\n"
        "                });\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Export Filtered Data to CSV\n"
        "        function exportDataCSV() {\n"
        "            const data = activeSheet === \'Ton\' ? rawDataTon : rawDataTK;\n"
        "            if (!data || data.length === 0) {\n"
        "                showToast(\'Không có dữ liệu để xuất!\', \'error\');\n"
        "                return;\n"
        "            }\n"
        "\n"
        "            let csvContent = \"data:text/csv;charset=utf-8,\\uFEFF\";\n"
        "            \n"
        "            if (activeSheet === \'Ton\') {\n"
        "                csvContent += \"STT,Số HĐ,Khách Hàng,Block,Tồn Giờ,Lần Hẹn,CL Lặp,Nhân Sự,Quản Lý,SOS,Kiểm Soát,Ghi Chú\\n\";\n"
        "                data.forEach((d, i) => {\n"
        "                    const status = auditStatuses[d.id] || \'\';\n"
        "                    csvContent += `\"${i+1}\",\"${d.id}\",\"${d.customerName}\",\"${d.block}\",\"${d.tonGio}\",\"${d.lanHen}\",\"${d.clLap}\",\"${d.nhanSu}\",\"${d.quanLy}\",\"${d.sos}\",\"${status}\",\"${d.ghiChu}\"\\n`;\n"
        "                });\n"
        "            } else {\n"
        "                csvContent += \"STT,Số HĐ,Khách Hàng,Block,Loại CV,Nhân Sự,Quản Lý,Ghi Chú\\n\";\n"
        "                data.forEach((d, i) => {\n"
        "                    csvContent += `\"${i+1}\",\"${d.id}\",\"${d.customerName}\",\"${d.block}\",\"${d.loaiCV}\",\"${d.nhanSu}\",\"${d.quanLy}\",\"${d.ghiChu}\"\\n`;\n"
        "                });\n"
        "            }\n"
        "\n"
        "            const encodedUri = encodeURI(csvContent);\n"
        "            const link = document.createElement(\"a\");\n"
        "            link.setAttribute(\"href\", encodedUri);\n"
        "            link.setAttribute(\"download\", `Export_Dashboard_${activeSheet}_${new Date().toISOString().slice(0,10)}.csv`);\n"
        "            document.body.appendChild(link);\n"
        "            link.click();\n"
        "            document.body.removeChild(link);\n"
        "\n"
        "            showToast(\'Đã xuất file CSV thành công!\', \'success\');\n"
        "        }\n"
        "\n"
        "        // Dark Mode Toggle Switcher\n"
        "        function toggleDarkMode() {\n"
        "            const html = document.documentElement;\n"
        "            if (html.classList.contains(\'dark\')) {\n"
        "                html.classList.remove(\'dark\');\n"
        "                html.classList.add(\'light\');\n"
        "            } else {\n"
        "                html.classList.remove(\'light\');\n"
        "                html.classList.add(\'dark\');\n"
        "            }\n"
        "            if (rawDataTon.length > 0 || rawDataTK.length > 0) {\n"
        "                applyFiltersAndRenderTable();\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Initialize Dashboard on Page Load\n"
        "        window.onload = function() {\n"
        "            initDefaultData();\n"
        "            renderDashboard();\n"
        "        };\n"
        "\n"
        "        function renderDashboard() {\n"
        "            renderKPIs();\n"
        "            renderFilters();\n"
        "            applyFiltersAndRenderTable();\n"
        "        }\n"
        "    </script>\n"
        "</body>\n"
        "</html>"""

if __name__ == "__main__":
    html = generate_html()
    print(html)
    # You can also write to a file:
    # with open("output.html", "w") as f:
    #     f.write(html)
